// project-root/projects.js
// 一覧・詳細で共通に使う作品データ

const projects = [
  {
    id: "marugotofes-2025",
    slug: "marugotofes-2025",
    title: "まるごと祭2025 ティザー",
    desc: "モーショングラフィックス / 監督・編集",
    year: "2025",
    tags: ["Animation"],
    thumb: "/img/projects/marugotofes.png",
    // hoverで動画にしたい場合だけ指定
    video: "/video/projects/まるごと祭2025.mp4",

    // 詳細ページ用（後で使う）
    images: ["/img/projects/marugotofes/01.png", "/img/projects/marugotofes/02.png", "/img/projects/marugotofes/03.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/FTI6JqU4zao?si=8UOHcgBwtpTp0ZbO",
  },
  {
    id: "seisyunsai-2026",
    slug: "seisyunsai-2026",
    title: "青春祭2026 ティザー",
    desc: "アニメーション / 監督・編集",
    year: "2026",
    tags: ["Animation"],
    thumb: "/img/projects/seisyunsai.png",
    video: "/video/projects/seisyunsai.mp4",
    images: ["/img/projects/seisyunsai/11.png", "/img/projects/seisyunsai/12.png", "/img/projects/seisyunsai/13.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/sQ-MlzUglhU?si=kyx1t4UKuptYratM",
  },
  {
    id: "kaieiga",
    slug: "kaieiga",
    title: "邂",
    desc: "短編映画 / 監督・編集",
    year: "2024",
    tags: ["Movie", "Directing"],
    thumb: "/img/projects/kaieiga.png",
    video: "/video/projects/邂1分ver.mov",
    images: ["/img/projects/kaieiga/01.png", "/img/projects/kaieiga/02.png", "/img/projects/kaieiga/03.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/lr5k4PWpGlE?si=Xu9EbIXop7sLAGMG",
  },
  {
    id: "sakanuhana",
    slug: "sakanuhana",
    title: "咲かぬ花",
    desc: "短編映画 / 監督・編集",
    year: "2025",
    tags: ["Movie", "Directing"],
    thumb: "/img/projects/sakanuhana.png",
    video: "/video/projects/咲かぬ花.mov",
    images: ["/img/projects/sakanuhana/21.png", "/img/projects/sakanuhana/22.png", "/img/projects/sakanuhana/23.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/nfpBrb2R6eY?si=5rHIkpgf-uNjQRb7",
  },
  {
    id: "burikinodance-typopv",
    slug: "burikinodance-typopv",
    title: "ブリキノダンス 文字PV",
    desc: "モーショングラフィックス / 編集",
    year: "2024",
    tags: ["Animation"],
    thumb: "/img/projects/burikinodance.png",
    video: "/video/projects/ブリキノダンス.mp4",
    images: ["/img/projects/burikinodance/31.png", "/img/projects/burikinodance/32.png", "/img/projects/burikinodance/33.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/co-H31EeKi4?si=dVVooqvrpWKdJe_2",
  },
      {
    id: "eigatomori",
    slug: "eigatomori",
    title: "映画と森Night",
    desc: "イベント企画 / 企画・演出・映像制作",
    year: "2025",
    tags: ["Documentary", "EventManagement","Directing"],
    thumb: "/img/projects/eigatomori.jpg",
    video: "/video/projects/eigatomori.mov",
    images: ["/img/projects/eigatomori/41.png", "/img/projects/eigatomori/42.png", "/img/projects/eigatomori/43.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/NNxy-ZTM4k8?si=tEBqLz5uwXM0xkTS",
  },
    {
    id: "domedirect",
    slug: "domedirect",
    title: "DOME Direct",
    desc: "モーショングラフィックス / 監督・編集",
    year: "2025",
    tags: ["Animation"],
    thumb: "/img/projects/domedirect.png",
    video: "/video/projects/domedirect.mov",
    images: ["/img/projects/domedirect/51.png", "/img/projects/domedirect/52.png", "/img/projects/domedirect/53.png"],
    youtubeEmbedUrls: [
      "https://www.youtube.com/embed/W5K3QnChElI?si=uTvsCX2zv-ZC9l8e",
      "https://www.youtube.com/embed/0DLpRHItUA8?si=48dWLk0IJWgx5pgQ"
    ],
  },
    {
    id: "rougelatte",
    slug: "rougelatte",
    title: "Rougelatte",
    desc: "ステージ演出 / アニメーション / プロジェクションマッピング",
    year: "2025",
    tags: ["Animation", "ProjectionMapping"],
    thumb: "/img/projects/rougelatte.jpg",
    video: "/video/projects/rougelatte.mp4",
    images: ["/img/projects/rougelatte/61.jpg", "/img/projects/rougelatte/62.png", "/img/projects/rougelatte/63.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/n2APxQlWjt0?si=KF8Pn3i2nxp2NSUs",
  },
      {
    id: "yukichikenken",
    slug: "yukichikenken",
    title: "Yukichi&KenKen結婚式映像",
    desc: "ドキュメンタリー / 監督・編集",
    year: "2025",
    tags: ["Documentary", "Directing"],
    thumb: "/img/projects/yukichikenken.png",
    video: "/video/projects/yukichikenken.mov",
    images: ["/img/projects/yukichikenken/71.png", "/img/projects/yukichikenken/72.png", "/img/projects/yukichikenken/73.png"],
    youtubeEmbedUrl: "",
  },
        {
    id: "mangetsuityou",
    slug: "mangetsuityou",
    title: "満月銀杏ProjectionMapping",
    desc: "アニメーション / プロジェクションマッピング",
    year: "2025",
    tags: ["Animation", "ProjectionMapping"],
    thumb: "/img/projects/mangetsuityou.JPEG",
    video: "/video/projects/IMG_1124.mov",
    images: ["/img/projects/mangetsuityou/81.JPEG", "/img/projects/mangetsuityou/82.JPEG", "/img/projects/mangetsuityou/83.JPEG"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/NNxy-ZTM4k8?si=tEBqLz5uwXM0xkTS",
  },
          {
    id: "summerschool2023",
    slug: "summerschool2023",
    title: "SummerSchool2023",
    desc: "ドキュメンタリー / 監督・編集",
    year: "2023",
    tags: ["Documentary", "Directing"],
    thumb: "/img/projects/summerschool2023.png",
    video: "/video/projects/summerschool.mp4",
    images: ["/img/projects/summerschool2023/91.png","/img/projects/summerschool2023/93.png","/img/projects/summerschool2023/94.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/ETNxeqHXAAI",
  },
            {
    id: "TECH MUSIC LIVE",
    slug: "techmusiclive",
    title: "TECH MUSIC LIVE オープニング映像",
    desc: "アニメーション / 監督・編集",
    year: "2025",
    tags: ["Animation"],
    thumb: "/img/projects/techmusic.png",
    video: "/video/projects/techmusiclive.mov",
    images: ["/img/projects/techmusiclive/101.png","/img/projects/techmusiclive/102.png","/img/projects/techmusiclive/103.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/QQaFkdy-6D0?si=WZOK3rdopmZxdcI0",
  },
              {
    id: "LAUNICA LP映像",
    slug: "launica-lp",
    title: "LAUNICA LP映像",
    desc: "アニメーション / モーショングラフィックス",
    year: "2025",
    tags: ["Animation"],
    thumb: "/img/projects/launica.png",
    video: "/video/projects/launica.mp4",
    images: ["/img/projects/launica/111.png","/img/projects/launica/112.png","/img/projects/launica/113.png"],
    youtubeEmbedUrl: "https://www.youtube.com/embed/unWDM_4JuN4?si=c1a2IZsgqYhsr3ff",
  },
                {
    id: "撮り旅 2023/2025",
    slug: "soukibin",
    title: "撮り旅 2023/2025",
    desc: "監督・編集",
    year: "2023-2025",
    tags: ["Directing"],
    thumb: "/img/projects/toritabi.png",
    video: "/video/projects/撮り旅２.mov",
    images: ["/img/projects/toritabi/121.png","/img/projects/toritabi/122.png","/img/projects/toritabi/124.png"],
    youtubeEmbedUrls: [
    "https://www.youtube.com/embed/09zV9ToiIj8?si=PIqVlpmJ7ZNXL6Z8",
  ],
  },
                  {
    id: "marugotofes",
    slug: "marugotofes",
    title: "まるごと祭 EndingMovie 2023-2025",
    desc: "監督・編集 / ドキュメンタリー",
    year: "2023-2025",
    tags: ["Directing"],
    thumb: "/img/projects/133.png",
    video: "/video/projects/marugotofes.mov",
    images: ["/img/projects/marugotofesending/131.png","/img/projects/marugotofesending/132.png","/img/projects/marugotofesending/133.png"],
    youtubeEmbedUrls: [],
  },




  // ✅ ここから下にいくらでも追加OK（コピペして slug だけ必ずユニークに）
];

module.exports = projects;
